apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vector-1
  template:
    metadata:
      labels:
        app: vector-1
    spec:
      volumes:
        - name: config
          configMap:
            name: vector-config
        - name: log-storage
          persistentVolumeClaim:
            claimName: vector-log-pvc-1
        - name: vector-data
          emptyDir: {}
      containers:
        - name: vector
          image: timberio/vector:0.41.X-debian
          args: ["--config", "/etc/vector/vector.yaml"]
          ports:
            - containerPort: 24224
              name: fluent
            - containerPort: 8686
              name: api
          volumeMounts:
            - name: config
              mountPath: /etc/vector
            - name: log-storage
              mountPath: /logs
            - name: vector-data
              mountPath: /vector-data-dir
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
