apiVersion: v1
kind: Service
metadata:
  name: vector
spec:
  selector:
    app: vector
  ports:
    - name: fluent
      port: 24224
      targetPort: 24224
      protocol: TCP
    - name: api
      port: 8686
      targetPort: 8686
      protocol: TCP
